DWES (Jorge)/Tema-3/Tema3/urls.py
from django.urls import path, re_path
from .import views


urlpatterns = [
    path('',views.index,name='index'),
    path('libros/listar',views.listar_libros,name='lista_libros'),
    path("libros/<int:id_libro>/", views.dame_libro,name="dame_libro"),
    path("libros/<int:anyo_libro>/<int:mes_libro>", views.dame_libros_fecha,name="dame_libros_fecha"),
    path("libros/listar/<str:tipo>/", views.dame_libros_idioma,name="dame_libros_idioma"),
    path("biblioteca/<int:id_biblioteca>/libros/<str:texto_libro>", views.dame_libros_biblioteca,name="dame_libros_biblioteca"),
    path('biblioteca/<int:id_biblioteca>/',views.dame_libros_biblioteca,name='dame_biblioteca'),
    path('ultimo-cliente-libro/<int:libro>',views.dame_ultimo_cliente_libro,name='ultimo_cliente_libro'),
    re_path(r"^filtro[0-9]$", views.libros_no_prestados,name="libros_no_prestados"),
]

DWES (Jorge)/Tema-3/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Tema3.urls")),
]

DWES (Jorge)/Tema-3/Tema3/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Biblioteca(models.Model):
    direccion = models.TextField()

class Autor(models.Model):
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=200, blank=True)
    edad = models.IntegerField(null = True)
    
class Libro(models.Model):
    IDIOMAS = [
        ("ES", "Español"),
        ("EN", "Inglés"),
        ("FR", "Francés"),
        ("IT", "Italiano"),
    ]
    
    nombre = models.CharField(max_length=200)
    tipo = models.CharField(
        max_length=2,
        choices=IDIOMAS,
        default="ES",
    )
    
    descripcion = models.TextField()
    fecha_publicacion = models.DateField()
    biblioteca = models.ForeignKey(Biblioteca, on_delete=models.CASCADE)
    autores = models.ManyToManyField(Autor)
    
class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.CharField(max_length=200, unique=True)
    puntos = models.FloatField(default=5.0, db_column="puntos_biblioteca")
    
    libros = models.ManyToManyField(Libro, through='Prestamos', related_name="libros")
    libros_preferidos = models.ForeignKey(Libro, on_delete = models.CASCADE, related_name="favoritos")

class DatosCliente(models.Model):
    cliente = models.OneToOneField(Cliente, on_delete = models.CASCADE)
    direccion = models.TextField()
    gustos = models.TextField()
    telefono = models.IntegerField()
    
class Prestamos(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    libro = models.ForeignKey(Libro, on_delete=models.CASCADE)
    fecha_prestamo = models.DateTimeField(default=timezone.now)

DWES (Jorge)/Tema-3/Tema3/views.py
from django.shortcuts import render
from django.db.models import Q
from .models import Libro, Cliente

# Create your views here.

def index(request):
    return render(request,'index.html') 

def listar_libros(request):
    libros = Libro.objects.select_related("biblioteca").prefetch_related("autores")
    libros = libros.all()
    return render(request, 'libro/lista.html',{"libros_mostrar":libros})

def dame_libro(request,id_libro):
    QSlibro = Libro.objects.select_related("biblioteca").prefetch_related("autores")
    libro = QSlibro.get(id=id_libro)
    return render(request, 'libro/libro.html',{"libro_mostrar":libro})

def dame_libros_fecha(request, anyo_libro, mes_libro):
    libros = Libro.objects.prefetch_related("autores").select_related("biblioteca")
    libros = libros.filter(fecha_publicacion__year=anyo_libro, fecha_publicacion__month=mes_libro)
    return render(request, 'libro/lista.html',{"libros_mostrar":libros})

def dame_libros_idioma(request, tipo):
    libros = Libro.objects.select_related("biblioteca").prefetch_related("autores")
    libros.filter(Q(tipo=tipo) | Q(tipo="ES")).order_by("fecha_publicacion")
    return render(request, 'libro/lista.html',{"libros_mostrar":libros})

def dame_libros_biblioteca(request,id_biblioteca,texto_libro):
    libros = Libro.objects.select_related("biblioteca").prefetch_related("autores")
    libros = libros.filter(biblioteca=id_biblioteca).filter(descripcion__contains=texto_libro).order_by("-nombre")
    return render(request, 'libro/lista.html',{"libros_mostrar":libros})

def dame_ultimo_cliente_libro(request,libro):
    cliente = Cliente.objects.filter(prestamos__libro=libro).order_by("-prestamos__fecha_prestamo")[:1].get()
    return  render(request, 'cliente/cliente.html',{"cliente":cliente})

def libros_no_prestados(request):
    libros = Libro.objects.select_related("biblioteca").prefetch_related("autores")
    libros = libros.filter(prestamos=None)
    return render(request, 'libro/lista.html',{"libros_mostrar":libros})

DWES (Jorge)/Tema-3/Tema3/templates/cliente/cliente.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
    <h1>Cliente</h1>    

    <div>
            <h2>Nombre: {{ cliente.nombre }} </h2>  
            <h3>Email: {{ cliente.email }}</h2>
            <h4>Puntos: {{ cliente.puntos}}</h4>
    </div>

    </body>
</html>

DWES (Jorge)/Tema-3/Tema3/templates/index.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
    <h1>BIBLIOTECA ONLINE</h1>

    <h2>Listado de enlaces</h2>
    <ul>
        <li><a href="{% url 'lista_libros' %}">Libros</a></li>
        <li><a href="{% url 'dame_libro' 10 %}">Ver libro 10</a></li>
    </ul>
    <ul>
        <li><a href="{% url 'dame_libros_fecha' 2021 1 %}">Libros del año 2021 y del mes de Enero</a></li>
        <li><a href="{% url 'dame_libros_biblioteca' 1 'prueba' %}">Libros Biblioteca 1 con filtro de texto</a></li>
        <li><a href="{% url 'dame_libros_biblioteca' 2 'hel' %}">Libros Biblioteca 2 con filtro de texto</a></li>
        <li><a href="{% url 'dame_libros_biblioteca' 1 'pr' %}">Libros Biblioteca 1 con otro filtro de texto</a></li>
    </ul>
    <ul>
        <li><a href="{% url 'libros_no_prestados' %}">Libros No prestados</a></li>
    </ul>
    </body>
</html>

DWES (Jorge)/Tema-3/Tema3/templates/libro/libro.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
    <h1>Biblioteca</h1>

    <div>
            <h2>Nombre: {{ libro_mostrar.nombre }} </h2>
            <h2>Biblioteca {{ libro_mostrar.biblioteca.nombre }}</h2>
            <h2>Autores</h2>
            <ul>
                {% for autor in libro_mostrar.autores.all %}
                    <li>{{ autor.nombre }}</li>
                {% endfor%}
            </ul>
            <h3>Idioma: {{ libro_mostrar.get_idioma_display }}</h2>
    </div>
    </body>
</html>

DWES (Jorge)/Tema-3/Tema3/templates/libro/lista.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
    <h1>Biblioteca</h1>

    {% for libro in libros_mostrar %}
        <div>
            <h2>Nombre: {{ libro.nombre }} </h2>
            <h2>Biblioteca {{ libro.biblioteca.nombre }}</h2>
            <h2>Autores</h2>
            <ul>
                {% for autor in libro.autores.all %}
                    <li>{{ autor.nombre }}</li>
                {% endfor%}
            </ul>
            <p>Fecha Publicacion {{ libro.fecha_publicacion }}:
                <a href="{% url 'dame_libros_fecha' libro.fecha_publicacion.year libro.fecha_publicacion.month %}">
                    Pulsa para ver libros del mismo año y mes
                </a>
            </p>
            <h3>Idioma: {{ libro.get_tipo_display }}
                <a href="{% url 'dame_libros_idioma' libro.tipo %}">
                    Pulsa para ver libros del mismo idioma o Español
                </a>
            </h3>
            <h3>
                Último cliente que se llevo el libro:
                <a href="{% url 'ultimo_cliente_libro' libro.id %}">
                    Pulsa para ver el último cliente
                </a>
            </h3>   
        </div>
    {% endfor %}

    </body>
</html>